TIMEOUT=0

# Имя пункта меню (любое)
:TOS
    # Обязательно укажите протокол!
    PROTOCOL=limine
    
    # Путь к ядру внутри ISO. 
    # Три слеша 'boot:///' означают корень загрузочного диска.
KERNEL_PATH=boot:///boot/kernel.elf