timeout: 0

# расширение окна загрузчика
interface_resolution: 100x100

# информация о загрзку 
verbose: no

# Титул
interface_branding: TOS (Limine)
interface_branding_color: 5727F5 

# обои
wallpaper: boot():/img.jpg

# первая пара отвечает за прозрачнось
term_background: 40000000

# размер текста
# маштабирование по осям
#term_font_scale: 1x1 
#1 занчение по идеи игнорируется читай в доке
term_font_size: 8x20

# название оси
/TOS
    protocol: limine
    # разрешение экрана последний параметр сколько бит на пиксель
    resolution: 100x100x32
    path: boot():/boot/kernel.elf


